name: Build and Upload RPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload RPM as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpm-package
          path: RPMS/x86_64/webFimos-1.0-1.el8.x86_64.rpm
